# Generated by Django 6.0 on 2025-12-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('technology', models.CharField(max_length=200, verbose_name='Tecnologías Usadas')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Captura/Imagen')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Enlace a GitHub')),
                ('live_link', models.URLField(blank=True, null=True, verbose_name='Enlace del Proyecto en Vivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
