# Generated by Django 5.1.6 on 2025-12-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre de la Certificación')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Imagen del Certificado')),
                ('date_issued', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['-date_issued'],
            },
        ),
    ]
